kind: Namespace
apiVersion: v1
metadata:
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signup
  namespace: default
spec:
  selector:
    matchLabels:
      app: signup
  replicas: 3
  template:
    metadata:
      labels:
        app: signup
    spec:
      containers:
        - name: signup
          # enter the path to your image, be sure to include the correct region prefix
          image: iad.ocir.io/natdcshjumpstartprod/signup:${BUILDRUN_HASH}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: node-gettingstarted-service
  namespace: default
  annotations: 
    service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: signup